In [ ]:
#本讲主要内容
#1.利用内置函数读取与操作文本文件
#2.利用pandas读取与操作文本文件  pandas适合处理有标签的数据
#3.Numpy基本操作

In [2]:
###内置函数读取与操作文本文件
#文本文件操作的步骤：打开->读取->数据处理->写入->关闭，不要忘了关闭
f=open('d:\\data\\score.txt')   #\\意思是避免翻译字符，如果在前面加r就可以避免
s=f.read()
s                               #\t是制表符位，是其中的空格  \n是换行


'考号\t\t程序设计\t生物\t科学\n10153450101\t82\t78\t78\n10153450102\t72\t71\t71\n10153450103\t82\t32\t32\n10153450104\t62\t72\t72\n10153450105\t62\t70\t70\n10153450106\t85\t90\t85\n10153450107\t65\t69\t69\n10153450108\t74\t50\t50\n10153450109\t80\t28\t28\n10153450110\t80\t60\t60'

In [3]:
f.readline()   #已经读过了，所以

''

In [4]:
f.close()

In [5]:
f=open('d:\\data\\score.txt')
f.readline()

'考号\t\t程序设计\t生物\t科学\n'

In [6]:
s=f.readlines()
print(s)

['10153450101\t82\t78\t78\n', '10153450102\t72\t71\t71\n', '10153450103\t82\t32\t32\n', '10153450104\t62\t72\t72\n', '10153450105\t62\t70\t70\n', '10153450106\t85\t90\t85\n', '10153450107\t65\t69\t69\n', '10153450108\t74\t50\t50\n', '10153450109\t80\t28\t28\n', '10153450110\t80\t60\t60']


In [4]:
f=open(r'd:\data\create.txt','w')
f.close


<function TextIOWrapper.close()>

In [3]:
#如何删除文件
import os
os.chdir(r'd:\data')
if os.path.exists("create.txt"):
    os.remove("create.txt")   
    print("删除成功")
else:
    print('文件不存在')

文件不存在


In [3]:
#$$$$$$$$ex5-1
f1=open(r'd:\data\score.txt')
head=f1.readline()
s=f1.readline()
print(s)

10153450101	82	78	78



In [4]:
import re
ls=re.split('\t',s)
ls

['10153450101', '82', '78', '78\n']

In [5]:
lsn=list(map(lambda x:int(x),ls))
lsn

[10153450101, 82, 78, 78]

In [6]:
sno=lsn[0]
ssum=lsn[1]+lsn[2]+lsn[3]
if ssum>=260:
    grade='优秀'
elif ssum>=180:
    grade='及格'
else:
    grade='不及格'
    

In [10]:
f2=open(r'd:\data\level.txt','w')
f2.write(str(sno)+'\t'+grade)
f1.close
f2.close

<function TextIOWrapper.close()>

In [7]:
#$$$$$$ex5-2
f1=open(r'd:\data\score.txt')
head=f1.readline()
import os
import re
os.chdir(r'd:\data')      #当指定工作路径之后就不用再说明文件位置
with open('level.txt','w') as f2:     ####使用with open可以避免忘记 close
    for row in f1:
        line=re.split('\t',row)
        lsn=list(map(lambda x:int(x),line))
        sno=lsn[0]
        ssum=lsn[1]+lsn[2]+lsn[3]
        if ssum>=260:
            grade='优秀'
        elif ssum>=180:
            grade='及格'
        else:
            grade='不及格'
        f2.write(str(sno)+'\t'+grade+'\n')
    f1.close

In [10]:
import os
os.chdir(r'd:\data')
import pandas as pd
import numpy as np
df=pd.read_csv('text.csv')
df

date         A         B         C         D Unnamed: 5
0  2016/1/1  0.051358 -0.464379  0.451372 -0.304687     #NAME?
1  2016/1/2 -1.374134 -0.178072  0.883113 -0.573064        NaN
2  2016/1/3  1.877980  0.627882  0.301245  0.252659        NaN
3  2016/1/4 -0.647477 -0.120387  2.348094 -2.390437        NaN
4  2016/1/5 -1.729381  0.730832  0.230677  0.623488        NaN
5  2016/1/6  0.567245 -2.081011 -1.747135 -0.408908        NaN

In [11]:
df1=pd.read_csv('text.csv',index_col='date')
df1

A         B         C         D Unnamed: 5
date                                                       
2016/1/1  0.051358 -0.464379  0.451372 -0.304687     #NAME?
2016/1/2 -1.374134 -0.178072  0.883113 -0.573064        NaN
2016/1/3  1.877980  0.627882  0.301245  0.252659        NaN
2016/1/4 -0.647477 -0.120387  2.348094 -2.390437        NaN
2016/1/5 -1.729381  0.730832  0.230677  0.623488        NaN
2016/1/6  0.567245 -2.081011 -1.747135 -0.408908        NaN

In [13]:
finnews=pd.read_csv('fintext5000.csv',sep='\t')
finnews.shape

(5000, 2)

In [7]:
finnews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
type    5000 non-null object
text    5000 non-null object
dtypes: object(2)
memory usage: 78.2+ KB


In [28]:
finnews.head()

type                                               text
0   基金  2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发...
1   基金  中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航...
2   基金  中美贸易摩擦多个行业有正向影响成长风格基金受关注近期中美贸易摩擦不断升级，其对于大类资产配置...
3   基金  中报泄密：三大机构投资者偏好迥异社保青睐医药中报泄密：三大机构投资者偏好迥异社保青睐医药社保...
4   基金  余额宝规模跷跷板传淘宝整肃基金旗舰店两马PK短期理财正酣余额宝规模跷跷板传淘宝整肃基金旗舰店...

In [50]:
finnews['text']

0       2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发...
1       中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航...
2       中美贸易摩擦多个行业有正向影响成长风格基金受关注近期中美贸易摩擦不断升级，其对于大类资产配置...
3       中报泄密：三大机构投资者偏好迥异社保青睐医药中报泄密：三大机构投资者偏好迥异社保青睐医药社保...
4       余额宝规模跷跷板传淘宝整肃基金旗舰店两马PK短期理财正酣余额宝规模跷跷板传淘宝整肃基金旗舰店...
5       定开债基遇大额赎回多只产品缩水九成年末流动性紧张叠加债券市场行情迟迟未现好转迹象，多只中长期...
6       93只“先知”基金股市调整前猛减仓上周A股市场的大幅下跌，对主动管理型基金来说是个坏消息，尤...
7       2017企业养老金上调最新消息：退休金上调能造成多大的基金压力？2017企业养老金上调最新消...
8       领跑者工行再备案一家私募“债转股”新模式开启为提高债转股效率，领跑者工商银行(行情60139...
9       房地产健康发展长效机制迈出实质步伐50只基金超配房地产刚刚结束的中央经济工作会议指出，要加快...
10      2017企业退休养老金上调最新消息:当下养老保险基金是收支平衡略企业退休人员涨工资2017企...
11      五大关键词回顾私募行业的2017过去的一年，对私募行业来说，是一个内涵丰富的年份。10万亿+...
12      规模抢眼业绩欠佳背靠大树的国寿安保“气血不足今年以来，国信安保主动权益类基金及偏债型基金，均...
13      工银新能源B净值下跌1.82%6月18日讯今日工银新能源B上涨0.00%，成交0.0万元。截...
14      公募基金20年总回报超过2万亿元公募基金20年20大事件20年前的今天，中国第一家公募基金公...
15      诺安行业轮动混合基金什么时候发行具体发行时间介绍诺安行业轮动混合基金什么时候发行具体发行时间...
16      基金一季报：前十大公募基金重仓股集体曝光（除货基规模）随着2018年基金一季报披露结束，各只...
17      上周基金调研

In [43]:
finnews['text'].values

array(['2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金公告速递基金发行提示发行要素内容提要基金名称中证500医药卫生指数交易型开放式指数证券投资基金基金代码512303基金类型股票型管理人南方基金管理有限公司托管人中国农业银行（行情，问诊）股份有限公司发行起始日期2014年10月9日发行截止日期2014年10月30日投资范围主要投资于标的指数成份股、备选成份股。为更好地实现投资目标，本基金可少量投资于非成份股（包含中小板、创业板及其他经中国证监会核准发行的股票）、衍生工具（权证、股指期货等）、债券资产（国债、金融债、企业债、公司债、次级债、可转换债券、分离交易可转债、央行票据、中期票据、短期融资券等）、资产支持证券、债券回购、银行存款等固定收益类资产、现金资产、货币市场工具以及中国证监会允许基金投资的其他金融工具。在建仓完成后，本基金投资于标的指数成份股、备选成份股的资产比例不低于基金资产净值的95%，且不低于非现金基金资产的80%。发行要素内容提要基金名称中金纯债债券型证券投资基金基金代码A类000801，C类000802基金类型债券型管理人中金基金管理有限公司托管人中国建设银行（行情，问诊）股份有限公司发行起始日期2014年9月29日发行截止日期2014年10月29日投资范围投资于债券类资产不低于基金资产的80%，现金或到期日在一年以内的政府债券合计不低于基金资产净值的5%。发行要素内容提要基金名称广发中证百度百发策略100指数型证券投资基金基金代码A类基金份额的基金代码为：000826；E类基金份额的基金代码为：000827。基金类型股票型管理人广发基金管理有限公司托管人兴业银行（行情，问诊）股份有限公司发行起始日期2014年10月20日发行截止日期2014年10月28日（',
       '中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航母抄底主题基金中国首艘国产航母下水直播视频完整版国产001a航母下水直播地址4月23日是中国一年一度的海军建军节，今年的海军节有可能还将会迎来一件大喜事--中国第一艘国产航母001A型航母或将在这一天举行下水典礼。如果国产航母下水的话，则意味着中国新航母建造工程将进

In [52]:
finnews.describe()

type                                               text
count   5000                                               5000
unique    10                                               5000
top       外汇  日本高铁再出事故：JR西日本列车刹车部件脱落日本高铁再出事故：JR西日本列车刹车部件脱落【环...
freq     500                                                  1

In [27]:
finnews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
type    5000 non-null object
text    5000 non-null object
dtypes: object(2)
memory usage: 78.2+ KB


In [14]:
#增加列并填充值
from  datetime import date
date=str(date.today())
finnews['date']=date
finnews.head()

type                                               text        date
0   基金  2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发...  2020-12-07
1   基金  中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航...  2020-12-07
2   基金  中美贸易摩擦多个行业有正向影响成长风格基金受关注近期中美贸易摩擦不断升级，其对于大类资产配置...  2020-12-07
3   基金  中报泄密：三大机构投资者偏好迥异社保青睐医药中报泄密：三大机构投资者偏好迥异社保青睐医药社保...  2020-12-07
4   基金  余额宝规模跷跷板传淘宝整肃基金旗舰店两马PK短期理财正酣余额宝规模跷跷板传淘宝整肃基金旗舰店...  2020-12-07

In [51]:
#按属性值选择行数据
finnews_fund=finnews[finnews['type']=='基金']
finnews_fund

type                                               text        date  \
0     基金  2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发...  2020-11-08   
1     基金  中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航...  2020-11-08   
2     基金  中美贸易摩擦多个行业有正向影响成长风格基金受关注近期中美贸易摩擦不断升级，其对于大类资产配置...  2020-11-08   
3     基金  中报泄密：三大机构投资者偏好迥异社保青睐医药中报泄密：三大机构投资者偏好迥异社保青睐医药社保...  2020-11-08   
4     基金  余额宝规模跷跷板传淘宝整肃基金旗舰店两马PK短期理财正酣余额宝规模跷跷板传淘宝整肃基金旗舰店...  2020-11-08   
5     基金  定开债基遇大额赎回多只产品缩水九成年末流动性紧张叠加债券市场行情迟迟未现好转迹象，多只中长期...  2020-11-08   
6     基金  93只“先知”基金股市调整前猛减仓上周A股市场的大幅下跌，对主动管理型基金来说是个坏消息，尤...  2020-11-08   
7     基金  2017企业养老金上调最新消息：退休金上调能造成多大的基金压力？2017企业养老金上调最新消...  2020-11-08   
8     基金  领跑者工行再备案一家私募“债转股”新模式开启为提高债转股效率，领跑者工商银行(行情60139...  2020-11-08   
9     基金  房地产健康发展长效机制迈出实质步伐50只基金超配房地产刚刚结束的中央经济工作会议指出，要加快...  2020-11-08   
10    基金  2017企业退休养老金上调最新消息:当下养老保险基金是收支平衡略企业退休人员涨工资2017企...  2020-11-08   
11    基金  五大关键词回顾私募行业的2017过去的一年，对私募行业来说，是一个内涵丰富的年份。10万亿+...  2020-11-08   
12    基金  规模抢眼业绩欠佳背靠大树的国寿安保“气血不足今年以来，国信安保主动权益类基金及偏债型基金，均...  2020-11-08   
13    基金  工银新能源B净值下跌1.82%6月18日讯今日工银新能源B上涨0.00%，成交0.0万元。截...  2020-11-08   
14    基金  公募基金20年总回报超过2万亿元公募基金20年20大事件20年前的今天，中国第一家公募基金公...  2020-11-08   
15    基金  诺安行业轮动混合基金什么时候发行具体发行时间介绍诺安行业轮动混合基金什么时候发行具体发行时间...  2020-11-08   
16    基金  基金一季报：前十大公募基金重仓股集体曝光（除货基规模）随着2018年基金一季报披露结束，各只...  2020-11-08   
17    基金  上周基金调研51家公司特种化工受关注上周基金公司继续密集调研，基金调研的上市公司达到51家，...  2020-11-08   
18    基金  基金震荡市调研科技股半年报预喜概念股或成“香饽饽”6月A股市场震荡之下，机构调研更注重精挑细...  2020-11-08   
19    基金  新股发行一览表5月8日新股申购一览表|基金打新进入薄利多销模式新股发行一览表5月8日新股申购...  2020-11-08   
20    基金  市场估值处于历史低位养老目标基金加速入市近日，14只第三批养老目标基金获批发行。至此，加上首...  2020-11-08   
21    基金  泓德基金总经理王德晓：走好脚下每步路稳健方能基业长青再过不到一个月，泓德基金就将迎来三周岁的...  2020-11-08   
22    基金  2015年2月偏股基金策略：优化配置静候反击2015年2月偏股基金策略：优化配置静候反击导语...  2020-11-08   
23    基金  公募红包雨：开年分红同比翻倍2018年开年，公募基金下起了红包雨。根据同花顺(300033)...  2020-11-08   
24    基金  公募基金10年来猛加仓!中国平安仍居重仓股宝座公募基金10年来最猛加仓!中国平安仍居重仓股第...  2020-11-08   
25    基金  招商移动股票产业股票净值上涨1.61%6月20日讯招商移动互联网产业股票型证券投资基金(简称...  2020-11-08   
26    基金  股票多空基金昨天多数上涨股指期货发挥对冲功能昨天A股市场大幅下跌，权益类基金自然难免受到波及...  2020-11-08   
27    基金  最新优质基金推荐。每日优质基金推荐（10月8日）互联网金融并购开启支付宝母公司强势控股天弘基...  2020-11-08   
28    基金  业绩榜单年年换两只基金最失落谨慎看待新科榜首2017年公募基金业绩排行榜已然出炉，名列排行榜...  2020-11-08   
29    基金  信达澳银基金陷多事之秋：“老鼠仓”案发子公司“踩雷”公募基金捕鼠行动收网，在业内低调多年的信...  2020-11-08   
..   ...                                                ...         ...   
470   基金  净值接连下折规模不断缩水分级基金如期进入告别模式近期，分级基金接连触发下折，而且规模也在持续...  2020-11-08   
471   基金  工银瑞信沪港深股票A净值上涨2.42%06月11日讯工银瑞信沪港深股票型证券投资基金(简称：...  2020-11-08   
472   基金  监管浇冷水货币基金缘何逆势大涨尽管流动性新规、规模排名剔除货基、暂缓审批新品等一系列针对货币...  2020-11-08   
473   基金  公募基金参与转融通业务终落地!这几类公募基金嗨了业内翘首以盼近3年之久的公募基金参与转融通业...  2020-11-08   
474   基金  公募迎来20周年“老十家”引领行业巨变20年前的3月，南方基金成立，成为中国公募基金的起始标...  2020-11-08   
475   基金  转债基金可作博反弹利器近期转债基金大涨10月份政策暖风频吹，A股和可转债市场有所回升。投资者...  2020-11-08   
476   基金  延迟退休最新消息:延迟退休年龄最新规定:养老基金入市只是一种选延迟退休最新消息:2017延迟...  2020-11-08   
477   基金  养老金上调-企业退休职工2016养老金调整最新消息:养老基金怎么选养老金上调-企业退休职工2...  2020-11-08   
478   基金  长期投资基金：如何挑选主动型基金?尽管我很喜欢指数基金，但是热爱主动型基金的网友也很多，最近...  2020-11-08   
479   基金  鹏华传媒分级B净值上涨4.90%6月24日讯今日鹏华传媒分级B上涨5.47%，成交5.47万...  2020-11-08   
480   基金  2017企业退休养老金上调最新消息:养老金入市参照社保基金运作企业退休人员涨工资2017养老...  2020-11-08   
481   基金  通过战略配售抓住新时代龙头南方配售基金拟任基金经理蒋秋洁表示，作为国内首批战略配售基金，南方...  2020-11-08   
482   基金  三季度公募基金新进重仓股集中曝光三季度公募基金新进重仓股集中曝光整体盈利达到860.09亿元...  2020-11-08   
483   基金  2018年基金分红逆市增加分红方式选择有讲究2018年，A股市场走势整体低迷，但基金分红却逆...  2020-11-08   
484   基金  沪港深基金业绩大涨未来形势还是有所希冀恒生指数悄然大涨，创下十年以来新高，港股市场低估值优势...  2020-11-08   
485   基金  百发计划昨日披露华夏基金联手百度激战互联网金融百发计划昨日披露华夏基金联手百度激战互联网金融...  2020-11-08   
486   基金  “爆款基金”一季度积极布局大消费金融爆款基金是过去几个月关注度很高的一个现象。根据基金一季报...  2020-11-08   
487   基金  QDII基金有望成年度最佳品种年内涨幅最高接近50%与震荡的股市和债市相比，以港股和美股为代...  2020-11-08   
488   基金  民生加银基金副总经理林海因个人健康原因离职民生加银基金管理有限公司今日发布公告，公司副总经理...  2020-11-08   
489   基金  广发聚惠混合增聘费逸为基金经理广发聚惠灵活配置混合型证券投资基金今日发布公告，增聘费逸为基金...  2020-11-08   
490   基金  华商主题精选混合增聘周海栋为基金经理华商主题精选混合型证券投资基金今日发布公告，增聘周海栋为...  2020-11-08   
491   基金  2015基金机构调研风向有改变蓝筹冷成

In [8]:
###apply的使用
import jieba

In [16]:
def segged_s(s):
    return ''.join(jieba.lcut(s))
df3=finnews['segged_text']=finnews['text'].apply(segged_s)
print(df3)

0       2014年10月14日基金发行提示（10月13日-10月17日）2014年10月14日基金发...
1       中国航母下水仪式视频直播国产首艘航母下水直播视频抄底主题基中国航母下水仪式视频直播首艘国产航...
2       中美贸易摩擦多个行业有正向影响成长风格基金受关注近期中美贸易摩擦不断升级，其对于大类资产配置...
3       中报泄密：三大机构投资者偏好迥异社保青睐医药中报泄密：三大机构投资者偏好迥异社保青睐医药社保...
4       余额宝规模跷跷板传淘宝整肃基金旗舰店两马PK短期理财正酣余额宝规模跷跷板传淘宝整肃基金旗舰店...
5       定开债基遇大额赎回多只产品缩水九成年末流动性紧张叠加债券市场行情迟迟未现好转迹象，多只中长期...
6       93只“先知”基金股市调整前猛减仓上周A股市场的大幅下跌，对主动管理型基金来说是个坏消息，尤...
7       2017企业养老金上调最新消息：退休金上调能造成多大的基金压力？2017企业养老金上调最新消...
8       领跑者工行再备案一家私募“债转股”新模式开启为提高债转股效率，领跑者工商银行(行情60139...
9       房地产健康发展长效机制迈出实质步伐50只基金超配房地产刚刚结束的中央经济工作会议指出，要加快...
10      2017企业退休养老金上调最新消息:当下养老保险基金是收支平衡略企业退休人员涨工资2017企...
11      五大关键词回顾私募行业的2017过去的一年，对私募行业来说，是一个内涵丰富的年份。10万亿+...
12      规模抢眼业绩欠佳背靠大树的国寿安保“气血不足今年以来，国信安保主动权益类基金及偏债型基金，均...
13      工银新能源B净值下跌1.82%6月18日讯今日工银新能源B上涨0.00%，成交0.0万元。截...
14      公募基金20年总回报超过2万亿元公募基金20年20大事件20年前的今天，中国第一家公募基金公...
15      诺安行业轮动混合基金什么时候发行具体发行时间介绍诺安行业轮动混合基金什么时候发行具体发行时间...
16      基金一季报：前十大公募基金重仓股集体曝光（除货基规模）随着2018年基金一季报披露结束，各只...
17      上周基金调研

In [12]:
seg_list = jieba.cut("我来到北京清华大学", cut_all=True)
print("全模式: " + "/ ".join(seg_list))  # 全模式

seg_list = jieba.cut("我来到北京清华大学", cut_all=False)
print("精准模式: " + "/ ".join(seg_list))  # 精确模式

seg_list = jieba.cut("他来到了网易杭研大厦")  # 默认是精确模式
print(", ".join(seg_list))

全模式: 我/ 来到/ 北京/ 清华/ 清华大学/ 华大/ 大学
精准模式: 我/ 来到/ 北京/ 清华大学
他, 来到, 了, 网易, 杭研, 大厦


In [13]:
###########$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$如何把这个数据按某一行元素进行降序或者升序排列

import jieba
def segged_s_len(s):
    return len(jieba.lcut(s))
finnews['Nwords']=finnews['text'].apply(segged_s_len)
finnews.sort_values(by='Nwords',ascending=False)

type                                               text  \
158    基金  2015年10月14日基金交易提示2015年10月14日基金交易提示基金拆分结果公告日：20...   
1765   保险  2017年北京医保政策|职工医疗保险报销比例范围2017年北京医保政策|职工医疗保险报销比例...   
2361   大盘  早盘A股缘何放量暴涨一大幕后真相曝光［编者按］今日早盘两市大盘高开高走，半年线和年线压力悉数...   
3391   银行  兰州银行不良率连续5年超同行去年逾期贷款增加27亿中国经济网编者按：兰州银行股份有限公司（简...   
4487   汽车  《车鲜知》:新1系三厢版售19.6-33.2万?《车鲜知》是个什么鬼？您可以把它当做一个研究...   
4847   债券  *ST中富：2015年6月12日将召开债券持有人会议特别提示：1、根据《珠海中富实业股份有限...   
4278   汽车  百人口碑评新车：争做精品的奇瑞瑞虎7各位网友大家好，第十期的《百人口碑评新车》与大家见面了。...   
2446   大盘  A股再创地量大盘反抽存五点希望A股再创地量大盘反抽存五点希望上周沪指继续寻底，沪指上攻400...   
2479   大盘  券商策略周报：7月行情望重演让子弹再飞一会儿上周市场继续上行，周初受沪港通利好兑现影响大盘高...   
2336   大盘  十大机构预测大势：2500点争夺战展开东吴证券：蓝筹获利回吐盘压力短线大盘震荡整固持续沪指涨...   
2348   大盘  上涨空间有限结构行情依旧每年的第一季度往往是流动性旺季和风险偏好提升的季节，一季度两市大盘也...   
4237   汽车  大搜车10亿打造车商联盟“家选”年内门店将超2000家大搜车创始人兼CEO姚军红新浪科技讯北...   
4305   汽车  发改委征求意见拟放宽汽车限购华为公开汽车相关业务「智东西」早报第1213期2019.4.18...   
2401   大盘  十大机构预测大势：2350点压力重重信达证券：场外资金正在逐步进场大盘重心逐步上移近日沪深两...   
3847   信托  信托业迈入16万亿元时代近日，中国信托业协会发布“2015年信托公司业务数据”，统计显示，在...   
2072   大盘  收评：尾杀曝光主力三大意图明日大盘走势收评：尾杀曝光主力三大意图明日走势消息面：1、国务院多...   
2442   大盘  板块轮动行情开启低估值蓝筹有望接棒编者按：沪指时隔40多个月收盘重新站上3000点关口，超级...   
4364   汽车  勇于突破传统边界-C2B模式定义汽车行业未来本文首发于微信公众号：哈佛商业评论。文章内容属作...   
4676   债券  中债资信ABS观察：2014我国资产证券化发展提速前景可期观点简述：2014年是我国资产证券...   
2371   大盘  历史机遇惊人的相似四大改革龙头喷薄而出有些股龄的股民都知道，10年国庆节行情的导火线就是险资...   
4098   汽车  买车真的可以freestyle吗？看完这5点还是让人心塞自2017年7月1日起实施的《汽车销...   
3970   信托  华宝证券：季节性因素影响集合信托发行量明显下滑2月信托产品无论是发行规模还是发行数量较今年1...   
4557   债券  中国债券市场的改革与发展近年来，在党中央、国务院的正确领导下，人民银行会同有关部门积极推动债...   
3534   信托  家族信托的中国玩法(图)一张图看懂家族信托慈传媒《中国慈善家》在考察了中国家族基金市场仅半年...   
4652   债券  吕琰：期待一规两引规定出台和讯债券消息第二届2014中国资产证券化高峰论坛于11月13日-1...   
34     基金  东方红林鹏:做投资不仅要赚钱要成为有价值的人林鹏最人性化访谈：做投资不仅仅是要赚钱，要成为有...   
3393   银行  脱离本源的同业存单业务亟需强化监管脱离本源的同业存单业务亟需强化监管高康闫静同业存单是银行业...   
4653   债券  债市牛市：上半场酣畅而任性下半场曲折而光明债市牛市：上半场酣畅而任性下半场曲折而光明国泰君安...   
3267   银行  贵州银行冲上市：全面不敌贵阳银行和茅台血缘更近中国经济网编者按：日前，贵州银行传出赴香港IP...   
3211   银行  上半年票据案已超百亿部分银行暂停纸票业务银监会《通知》指出，“本次‘回头看’的工作，是针对当...   
...   ...                                                ...   
3447   银行  楼文龙到任农业银行副行长农行高层洗牌重分工在年中杨琨协助调查、潘功胜上调央行后，农行高管团队...   
1928   保险  【2016职工生育保险规定】秦皇岛2016年职工生育保险费率调整最新【2016职工生育保险规...   
1712   保险  2016社保缴费基数调整_崇左2016企业职工养老保险缴费基数调整最2016社保缴费基数调整...   
1793   保险  2017永州失业保险最新消息：永州失业保险金调整发放标准提高85元2017永州失业保险最新消...   
1767   保险  2017天津失业保险最新消息：职工参加失业保险可申请技能提升补贴2017天津失业保险最新消息...   
1774   保险  2018昆明养老保险最新消息：昆明缴满3年养老保险租房也可落户2018昆明养老保险最新消息：...   
1932   保险  2017滕州失业保险最新消息：滕州失业保险金待遇上调到1030元2017滕州失业保险最新消息...   
1531   保险  2018青海失业保险最新消息：开展失业保险援企稳岗“护航行动”2018青海失业保险最新消息：...   
1613   保险  2017黑龙江养老保险最新消息：城镇职工一次性补缴养老保险超3年2017黑龙江养老保险最新消...   
1651   保险  杭州养老保险查询方法：杭州养老保险帐号如何查询？杭州养老保险查询方法：杭州养老保险帐号如何查...   
1858   保险  2017淮安养老保险最新消息：淮安企业职工养老保险周五上午截止缴2017淮安养老保险最新消息...   
1647   保险  2017南京失业保险最新消息_南京2017年度工伤保险待遇标准调整2017南京失业保险最新消...   
1926   保险  【武汉2017社保缴费基数】武汉城镇居民医疗保险报销比例一览表【武汉2017社保缴费基数】武...   
4995   债券    中证企业债100指数7月19日发布国内首只跨市场成分类信用债券指数面世，债券投资标的再添新丁。   
1778   保险  2018南京医保最新消息_南京2018年度居民医疗保险缴费标准2018南京医保最新消息_南京...   
1975   保险  【南京医疗保险报销比例】南京城镇居民医疗保险报销比例一览表【南京医疗保险报销比例】南京城镇居...   
1591   保险  2017玉林失业保险最新消息：参保职工可享职业技能提升补贴2017玉林失业保险最新消息：参保...   
1772   保险  【2016扬州工伤赔偿标准】扬州2016年工伤保险费率下调【2016扬州工伤赔偿标准】扬州2...   
1769   保险  重庆养老保险查询个人账户：重庆市个人养老保险余额如何查询？重庆养老保险查询个人账户：重庆市个...   
1589   保险  2017江苏养老保险最新消息_江苏省城乡居民基本养老保险政策解读2017江苏养老保险最新消息...   
1551   保险  2017呼伦贝尔工伤保险最新消息：提高工伤职工工伤保险待遇水平2017呼伦贝尔工伤保险最新消...   
1600   保险  苏州养老保险查询个人账户|苏州养老保险查询个人账户查询系统苏州养老保险查询个人账户|苏州养老...   
1959   保险  2017杭州社保缴费基数杭州城镇居民医疗保险报销比例一览表2017杭州社保缴费基数杭州城镇居...   
1562   保险  石家庄养老保险查询个人账户_石家庄养老保险查询个人账户查询入石家庄养老保险查询个人账户_石家...   
1911   保险  2017上饶养老保险最新消息：上饶为建档立卡贫困户代缴养老保险2017上饶养老保险最新消息：...   
3245   银行       银监会发文挺农业现代化鼓励银行单列涉农信贷计划⊙余额26.4万亿元，同比增长11.7%。   
3201   银行                          6月货币信贷增长超预期未来货币调控更重定向工具本报   
3365   银行                            阿里狼马云做银行网络放贷融资成本不超9)();   
3304   银行                             厦门国际银行再增资18亿零售短板尚待补齐本报   
3903   信托                                   2012年房地产信托兑付压力重重   

                                    

In [20]:
#如何储存为一个csv文件
r=range(0,5000,2)
selr=finnews.iloc[r,:]
selr.to_csv('finnews2500.csv',sep='\t',index=False)

In [26]:
import numpy as np
a=np.array([1,0.5,9,10])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a

array([ 1. ,  0.5,  9. , 10. ])

In [8]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c=np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
import os
os.chdir(r'd:\data')

In [12]:
f=open('corpus.txt','w')
f.write("'The sky is blue',\n,'The sky is blue and beautiful',\n,'Look at the bright blue sky!',\n,'Python is a great Programming language',\n,'Python and Java are popular Programming languages',\n,'Among Programming languages, both Python and Java are the most used in Analytics',\n,'The fox is quicker than the lazy dog',\n,'The dog is smarter than the fox',\n,'The dog, fox and cat are good friends'")
f.close()

In [13]:
#我终于发现了为什么，因为写完之后要读一遍，文件夹里面的东西才能显现出来
with open('corpus.txt') as f:
    s=f.read()
    print(s)


'The sky is blue',
,'The sky is blue and beautiful',
,'Look at the bright blue sky!',
,'Python is a great Programming language',
,'Python and Java are popular Programming languages',
,'Among Programming languages, both Python and Java are the most used in Analytics',
,'The fox is quicker than the lazy dog',
,'The dog is smarter than the fox',
,'The dog, fox and cat are good friends'


In [14]:
corpus=['The sky is blue',
'The sky is blue and beautiful',
'Look at the bright blue sky!',
'Python is a great Programming language',
'Python and Java are popular Programming languages',
'Among Programming languages, both Python and Java are the most used in Analytics',
'The fox is quicker than the lazy dog',
'The dog is smarter than the fox',
'The dog, fox and cat are good friends']

In [15]:
#list转化为np的array，array数组和list列表如何转化为Dataframe（数据框）
import pandas as pd
import numpy as np
labels = ['weather', 'weather', 'animals', 'food', 'food', 'animals','a','b','d']
corpus = np.array(corpus) #生成corpus的数组
corpus_df = pd.DataFrame ({'Document':corpus,'Category':labels}) #生成数据框，列名分别为Document, Category corpus_df
corpus_df

Document Category
0                                    The sky is blue  weather
1                      The sky is blue and beautiful  weather
2                       Look at the bright blue sky!  animals
3             Python is a great Programming language     food
4  Python and Java are popular Programming languages     food
5  Among Programming languages, both Python and J...  animals
6               The fox is quicker than the lazy dog        a
7                    The dog is smarter than the fox        b
8              The dog, fox and cat are good friends        d

In [16]:
#数据框转化为数组
corpus_np=corpus_df.keys
print('数据框里的什么我也不知道瞎猜的',corpus_np)
corpus_np=corpus_df['Document'].values
print('有没有能只转化一列的,可以！',corpus_np)
corpus_np=corpus_df.values
print('数据框里的列都转化了',corpus_np)

数据框里的什么我也不知道瞎猜的 <bound method NDFrame.keys of                                             Document Category
0                                    The sky is blue  weather
1                      The sky is blue and beautiful  weather
2                       Look at the bright blue sky!  animals
3             Python is a great Programming language     food
4  Python and Java are popular Programming languages     food
5  Among Programming languages, both Python and J...  animals
6               The fox is quicker than the lazy dog        a
7                    The dog is smarter than the fox        b
8              The dog, fox and cat are good friends        d>
有没有能只转化一列的,可以！ ['The sky is blue' 'The sky is blue and beautiful'
 'Look at the bright blue sky!' 'Python is a great Programming language'
 'Python and Java are popular Programming languages'
 'Among Programming languages, both Python and Java are the most used in Analytics'
 'The fox is quicker than the lazy dog' 'The dog is smart

In [17]:
#利用numpy对象的tolist()方法将nd.array转换为列表
corpus_ls=corpus_np.tolist()
corpus_ls

[['The sky is blue', 'weather'],
 ['The sky is blue and beautiful', 'weather'],
 ['Look at the bright blue sky!', 'animals'],
 ['Python is a great Programming language', 'food'],
 ['Python and Java are popular Programming languages', 'food'],
 ['Among Programming languages, both Python and Java are the most used in Analytics',
  'animals'],
 ['The fox is quicker than the lazy dog', 'a'],
 ['The dog is smarter than the fox', 'b'],
 ['The dog, fox and cat are good friends', 'd']]

In [18]:
#多维数组转换为数据框
corpus_df_new=pd.DataFrame(corpus_np,columns=['document','label'])
corpus_df_new

document    label
0                                    The sky is blue  weather
1                      The sky is blue and beautiful  weather
2                       Look at the bright blue sky!  animals
3             Python is a great Programming language     food
4  Python and Java are popular Programming languages     food
5  Among Programming languages, both Python and J...  animals
6               The fox is quicker than the lazy dog        a
7                    The dog is smarter than the fox        b
8              The dog, fox and cat are good friends        d

In [19]:
#数组的切片
corpus_np[:5]

array([['The sky is blue', 'weather'],
       ['The sky is blue and beautiful', 'weather'],
       ['Look at the bright blue sky!', 'animals'],
       ['Python is a great Programming language', 'food'],
       ['Python and Java are popular Programming languages', 'food']],
      dtype=object)

In [20]:
corpus_np[1:3,0:1]

array([['The sky is blue and beautiful'],
       ['Look at the bright blue sky!']], dtype=object)

In [21]:
corpus_np[1:3,0:2]

array([['The sky is blue and beautiful', 'weather'],
       ['Look at the bright blue sky!', 'animals']], dtype=object)

In [22]:





#$$$$$$$和矩阵  一样






In [23]:
ls=[1,3,5,2,0,6]
nls=np.array(ls)
ind=nls.argsort()[:3]

In [24]:
ind

array([4, 0, 3], dtype=int64)

In [25]:
###注意argsort()返回的数组从小到大的索引（索引是再列表中的位置，第一个值的索引为0，第二个值索引为1）

In [26]:
nls[ind]

array([0, 1, 2])

In [27]:

######介绍string的format方法！！！！！！！！
# 用{}代表占位符，直接位置传参
print('我是{}，喜欢{}！'.format('灭霸','打响指'))
# 我是灭霸，喜欢打响指！

# {}数量必须少于后面位置参数数量，不然报错
print('我是{}，喜欢{}，不喜欢{}。'.format('宙斯','放大抢人头','放空大','小短腿'))

print('我是{}，喜欢{}，不喜欢{}。'.format('宙斯','放大抢人头'))
# 报错误：IndexError: tuple index out of range

我是灭霸，喜欢打响指！
我是宙斯，喜欢放大抢人头，不喜欢放空大。


IndexError: tuple index out of range

In [28]:
corpus=['The sky is blue',
'The sky is blue and beautiful',
'Look at the bright blue sky!',
'Python is a great Programming language',
'Python and Java are popular Programming languages',
'Among Programming languages, both Python and Java are the most used in Analytics',
'The fox is quicker than the lazy dog',
'The dog is smarter than the fox',
'The dog, fox and cat are good friends']

In [32]:
query_doc = ['The fox is definitely smarter than the dog']

In [33]:
similarity = np.array([0., 0., 0., 0., 0., 0., 0.4263806,1., 0.37044049])
top_docs_index = pd.DataFrame({'Doc':corpus,'Similarity Score':similarity})
top_docs_index=np.array(corpus)


In [38]:
ind=similarity.argsort()[::-1][:-3]
similarity[ind]
top_docs_index[ind]

array(['The dog is smarter than the fox',
       'Among Programming languages, both Python and Java are the most used in Analytics',
       'Look at the bright blue sky!'], dtype='<U80')

In [40]:
print('Top 3 similar docs are') 
for index in similarity.argsort()[::-1][:-3]:
    print('Doc num:{} Similarity Score:{:.2f}\nDoc:{}'.format(index+1,similarity[index],corpus[index]))

Top 3 similar docs are
Doc num:8 Similarity Score:1.00
Doc:The dog is smarter than the fox
Doc num:7 Similarity Score:0.43
Doc:The fox is quicker than the lazy dog
Doc num:9 Similarity Score:0.37
Doc:The dog, fox and cat are good friends
Doc num:6 Similarity Score:0.00
Doc:Among Programming languages, both Python and Java are the most used in Analytics
Doc num:5 Similarity Score:0.00
Doc:Python and Java are popular Programming languages
Doc num:4 Similarity Score:0.00
Doc:Python is a great Programming language
